[package]
name = "winnie-os"
version = "0.1.0"
edition = "2024"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[[bin]]
name = "winnie-os"
path = "src/main.rs"
test = true
bench = false

[features]
default = []
test-panic = []
test-invalid-opcode = []
test-general-protection = []
test-page-fault = []
test-double-fault = []

[dependencies]
